version: '3.1'

services:

  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    command: npm run start-docker
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 4200:4200
    restart: always
    depends_on:
      - backend
  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports: 
      - '3000:3000'
    restart: always